"""
AWS CLI Generator - Marketplace Demo Script
Demonstrates core functionality using real queries.
"""
import os, sys
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(script_dir)
sys.path.insert(0, project_root)

from src.core.command_generator import generate_command_sync
from src.core.cli_formatter import format_human
from src.core.registry import registry

# Demo queries covering major AWS services
DEMO_QUERIES = [
    # S3 Operations
    ("list s3 buckets", "List all S3 buckets"),
    ("create an S3 bucket named demo-bucket in us-west-1", "Create S3 bucket with region"),
    
    # EC2 Operations
    ("list ec2 instances in us-west-1", "List EC2 instances in specific region"),
    
    # Lambda Operations
    ("list lambda functions in us-west-1", "List Lambda functions"),
    ("invoke lambda function named my-test-function in us-west-1", "Invoke Lambda function"),
    
    # DynamoDB Operations
    ("create dynamodb table Orders in us-west-1", "Create DynamoDB table"),
    ("list dynamodb tables", "List DynamoDB tables"),
    
    # IAM Operations
    ("create IAM user DevUser", "Create IAM user"),
    ("list IAM users", "List IAM users"),
    ("attach ReadOnlyAccess to user DevUser", "Attach policy to user"),
    
    # RDS Operations
    ("create an RDS instance testdb in us-west-1", "Create RDS instance"),
]

def print_header(text):
    """Print formatted header."""
    print("\n" + "="*70)
    print(f"  {text}")
    print("="*70)

def print_section(title):
    """Print section divider."""
    print(f"\n--- {title} ---")

def run_demo():
    """Run the marketplace demo."""
    
    print_header("AWS CLI GENERATOR - MARKETPLACE DEMO")
    print("\nA natural-language AWS CLI generator with built-in safety awareness")
    print("Designed for developers and AI-assisted workflows\n")
    
    # Initialize registry
    if not registry.services:
        registry.autodiscover()
    
    print(f"✓ Loaded {len(registry.services)} AWS service parsers")
    print(f"✓ Services: {', '.join(sorted(registry.services.keys()))}")
    
    print_header("DEMO QUERIES")
    
    for i, (query, description) in enumerate(DEMO_QUERIES, 1):
        print(f"\n{'='*70}")
        print(f"Demo {i}/{len(DEMO_QUERIES)}: {description}")
        print(f"{'='*70}")
        print(f"\nQuery: \"{query}\"\n")
        
        # Generate command
        result = generate_command_sync(query)
        
        # Show human-friendly output
        print(format_human(result, no_color=True))
        
        # Show metadata
        print(f"\nMetadata:")
        print(f"  Service: {result['meta']['service']}")
        print(f"  Confidence: {result['meta']['confidence']}")
        print(f"  Generated by: {result['meta']['generated_by']}")
        print(f"  Intent: {result['intent']}")
        
        if i < len(DEMO_QUERIES):
            input("\nPress Enter to continue...")
    
    print_header("DEMO COMPLETE")
    print("\nKey Features Demonstrated:")
    print("  ✓ Natural language understanding")
    print("  ✓ Multi-service support (S3, EC2, Lambda, DynamoDB, IAM, RDS)")
    print("  ✓ Region extraction and handling")
    print("  ✓ Safety classification (safe, warning, destructive)")
    print("  ✓ Human-friendly output formatting")
    print("  ✓ Metadata transparency")
    
    print("\nSecurity Guarantees:")
    print("  ✓ No AWS commands executed")
    print("  ✓ No credentials accessed or stored")
    print("  ✓ No AWS resources modified")
    print("  ✓ Stateless operation")
    
    print("\nIntegration Options:")
    print("  • MCP Server for Claude Desktop")
    print("  • Command-line interface (aws-nlp)")
    print("  • HTTP API for web applications")
    print("  • Python library for custom integrations")
    
    print("\n" + "="*70)
    print("Thank you for trying AWS CLI Generator!")
    print("="*70 + "\n")

def run_quick_demo():
    """Run a quick 3-query demo."""
    
    print_header("AWS CLI GENERATOR - QUICK DEMO")
    
    # Initialize registry
    if not registry.services:
        registry.autodiscover()
    
    quick_queries = [
        "list s3 buckets",
        "list ec2 instances in us-west-1",
        "create IAM user DevUser"
    ]
    
    for query in quick_queries:
        print(f"\n{'='*70}")
        print(f"Query: \"{query}\"")
        print(f"{'='*70}\n")
        
        result = generate_command_sync(query)
        print(format_human(result, no_color=True))
    
    print("\n" + "="*70)
    print("Quick demo complete!")
    print("="*70 + "\n")

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="AWS CLI Generator Demo")
    parser.add_argument("--quick", action="store_true", help="Run quick 3-query demo")
    args = parser.parse_args()
    
    if args.quick:
        run_quick_demo()
    else:
        run_demo()
